language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
    - pip install .

script: pytest -v

deploy:
  provider: pypi
  skip_existing: true
  user: jaromir.pufler
  password:
    secure: Un4IbU/7myRN4Mou5YtCk8oBMXoFM0ND45F8O9GHUhH99/RqVJ4AC9Z05q67ChbG9y48dSzLsdcg/ojquWn6TTou2UEnfPinlnWPXSUo1rE6LNNkfVUV5B7U68dVxcNy1Jbv2xTQfU2KBId7iFcZ5rRc98xkjwCHEKNsZn0nRqOC/tOzXmg1tcuRoqSgdg69HOBfjUWQJl+mKhvv5wZ9JFCZrn6beAF9dVWmPDKyZiTbyaug68famVqLkJ1rv8M/acQUzierDMA4QYudOXPSgmPCQEnoy7f/twGpRIeTvNTGba6nC6PtLIBSqPzNMwy6M3QQa5qVbg6cvszLlhg/epXb6hPCxC74VffPKdf9Gq+OczTwtU2t6sCsfghcTERRmHxeASMqg+TUozaUxXT13P1T+kmj9ZHiFSgYh3iPf/yz46qiL/O794Ql8CBWL/uj+PM1qKiDXpTgdSF4zZ7FUSEoShRvRZ9uxIOrMsPdwdEYHxwbddSyF3EXqY+1PBcIAVgbNTVPvFHyrmlHofnonNimEIk/Wd2KB2ycjF2SPjZvucDhQoHFTtcqxVY+vo3iZWiScw3/6cfLuEudX3Hz9rNQMawFeDBiH4D7fPT+Q52GWgnH185QNo4FTE6J7/SgL4ho/eDgsYFUOsNcilMkbyl62HXN13KkEW82u9xkTgI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: chuckyblack/pybabel-angularjs
